### ISSUE TITLE
add support for new WolfRPG version

### ISSUE THREAD

**Issue by galtgendo** [Sinflower/WolfDec#6]
Going by the page, first working version was around 2022/11/22, but it's still under heavy development.

Yet, it's already in active use and seems to be using a different key value.

The header still suggests it's DXArchive ver8.

**Comment by Sinflower** [comment]
Can you give me an example of where the new version is used, so I can use it for validation?

**Comment by galtgendo** [comment]
As usual, one of the first users is a dlsite title - a small game (around 300MB) currently in 24h top ten.
Though its demo is still using 2.295, which seems to be using yet different key.

**Comment by Sinflower** [comment]
Please try this version; it should be able to decrypt games made with WolfRPG 3.10, i.e., games using the new key.
Due to the way the encryption is implemented now, this version will probably only be able to decrypt the new games and crash for old ones. I am working on a fix for that and will hopefully release a new version capable of decrypting all known WolfRPG releases soon.
[WolfDec_wolf3.10.zip](https://github.com/Sinflower/WolfDec/files/10181164/WolfDec_wolf3.10.zip)

**Comment by galtgendo** [comment]
...so yeah, it seems to work, thanks...
Though, would be nice to have a more generic method of retrieving the key...
But giving that standard DXArchive compresses the index there are no as soft targets as the xored header previously was.
Unless Huffman compressed data has some regular elements that could be recognized...
One of the wolf files (probably the author's mistake as it was an empty archive) did have a regular structure where you could see the 7 byte repeating sequence that was the key as used by the code, but it was unclear what value was it been applied on...

**Comment by Sinflower** [comment]
I just released a new version containing the new key. I also rewrote the way decryption is called so that this version can decrypt both the new and the old archives.

Regarding the generic method, yeah, I know, but from what I can see, there is no data in the header that is fixed enough to use as a possible attack point. If you find something or have an idea feel free to let me know.
